export const initialBookings = [
  {
    id: "1000101",
    customerName: "Sheikh Hamdan Al Maktoum",
    whatsapp: "+971501234567",
    partnerId: "website",
    date: "2026-09-02",
    packageName: "VIP Safari Private Car 799AED",
    pickupLocation: "Atlantis The Palm, Crescent Rd, Dubai",
    roomNo: "Royal Suite 501",
    pickupTime: "3:30 PM to 4:00 PM",
    pax: 6,
    price: 799,
    driverId: "driver-adnan",
    status: "confirmed",
    addonName: "Falcon Photography",
    addonPrice: 40,
    carPax: "6/6",
    tourType: "pick_drop",
    paymentOption: "Payment on Arrival"
  },
  {
    id: "1000102",
    customerName: "Alexander Wright",
    whatsapp: "+971529876543",
    partnerId: "website",
    date: "2026-09-02",
    packageName: "Evening Safari 79AED",
    pickupLocation: "JW Marriott Marquis, Business Bay",
    roomNo: "Room 1408",
    pickupTime: "3:30 PM to 4:00 PM",
    pax: 4,
    price: 316,
    driverId: "driver-afzal",
    status: "confirmed",
    addonName: "",
    addonPrice: 0,
    carPax: "4/6",
    tourType: "pick_drop",
    paymentOption: "Payment on Arrival"
  },
  {
    id: "1000103",
    customerName: "Priya Sharma",
    whatsapp: "+971558765432",
    partnerId: "website",
    date: "2026-09-02",
    packageName: "Evening+Quadbike 199AED",
    pickupLocation: "Rove Downtown, Downtown Dubai",
    roomNo: "Room 812",
    pickupTime: "3:30 PM to 4:00 PM",
    pax: 2,
    price: 398,
    driverId: "driver-shahid",
    status: "confirmed",
    addonName: "Long Camel Ride",
    addonPrice: 60,
    carPax: "2/6",
    tourType: "pick_drop",
    paymentOption: "Payment on Arrival"
  },
  {
    id: "1000104",
    customerName: "Mohammed Al Nuaimi",
    whatsapp: "+971543210987",
    partnerId: "website",
    date: "2026-09-02",
    packageName: "Morning Safari 149AED",
    pickupLocation: "Address Sky View, Downtown",
    roomNo: "Room 2204",
    pickupTime: "8:00 AM to 8:30 AM",
    pax: 2,
    price: 298,
    driverId: "driver-abbasi",
    status: "completed",
    addonName: "",
    addonPrice: 0,
    carPax: "2/6",
    tourType: "pick_drop",
    paymentOption: "Payment on Arrival"
  },
  {
    id: "1000105",
    customerName: "Dmitry Ivanov",
    whatsapp: "+971561122334",
    partnerId: "website",
    date: "2026-09-03",
    packageName: "Private Morning 499AED",
    pickupLocation: "Five Palm Jumeirah, Dubai",
    roomNo: "Villa 12",
    pickupTime: "8:00 AM to 8:30 AM",
    pax: 4,
    price: 499,
    driverId: "driver-shahmir",
    status: "confirmed",
    addonName: "",
    addonPrice: 0,
    carPax: "4/6",
    tourType: "pick_drop",
    paymentOption: "Payment on Arrival"
  },
  {
    id: "1000106",
    customerName: "Sophie Martin",
    whatsapp: "+971507788990",
    partnerId: "website",
    date: "2026-09-03",
    packageName: "VIP Safari Shared 129AED",
    pickupLocation: "Hilton Dubai Jumeirah, JBR",
    roomNo: "Room 705",
    pickupTime: "3:30 PM to 4:00 PM",
    pax: 3,
    price: 387,
    driverId: "driver-ibadat",
    status: "confirmed",
    addonName: "Sheesha on Table",
    addonPrice: 50,
    carPax: "3/6",
    tourType: "pick_drop",
    paymentOption: "Payment on Arrival"
  },
  {
    id: "1000107",
    customerName: "Tariq Mansoor",
    whatsapp: "+971554433221",
    partnerId: "website",
    date: "2026-09-04",
    packageName: "Self Drive+Quadbike 149AED",
    pickupLocation: "Direct Desert Meeting Point, Al Awir",
    roomNo: "",
    pickupTime: "4:00 PM",
    pax: 2,
    price: 298,
    driverId: "driver-bangash",
    status: "confirmed",
    addonName: "",
    addonPrice: 0,
    carPax: "2/6",
    tourType: "self_drive",
    paymentOption: "Payment on Arrival"
  },
  {
    id: "1000108",
    customerName: "Fatima Zahra",
    whatsapp: "+971523344556",
    partnerId: "website",
    date: "2026-08-30",
    packageName: "Evening Safari 79AED",
    pickupLocation: "Sofitel Dubai The Obelisk",
    roomNo: "Room 1102",
    pickupTime: "3:30 PM to 4:00 PM",
    pax: 5,
    price: 395,
    driverId: "driver-adnan",
    status: "completed",
    addonName: "",
    addonPrice: 0,
    carPax: "5/6",
    tourType: "pick_drop",
    paymentOption: "Payment on Arrival"
  },
  {
    id: "1000109",
    customerName: "Carlos Gomez",
    whatsapp: "+971509988776",
    partnerId: "website",
    date: "2026-08-29",
    packageName: "VIP Safari Shared 129AED",
    pickupLocation: "Armani Hotel Dubai, Burj Khalifa",
    roomNo: "Room 3902",
    pickupTime: "3:30 PM to 4:00 PM",
    pax: 2,
    price: 258,
    driverId: "driver-afzal",
    status: "completed",
    addonName: "",
    addonPrice: 0,
    carPax: "2/6",
    tourType: "pick_drop",
    paymentOption: "Payment on Arrival"
  },
  {
    id: "1000110",
    customerName: "Chen Wei",
    whatsapp: "+971556677889",
    partnerId: "website",
    date: "2026-08-28",
    packageName: "Private Dubai Tour 499AED",
    pickupLocation: "Palazzo Versace Dubai, Jaddaf",
    roomNo: "Suite 601",
    pickupTime: "9:00 AM",
    pax: 4,
    price: 499,
    driverId: "driver-shahid",
    status: "completed",
    addonName: "",
    addonPrice: 0,
    carPax: "4/6",
    tourType: "pick_drop",
    paymentOption: "Payment on Arrival"
  },
  {
    id: "1000111",
    customerName: "Emily Watson",
    whatsapp: "+971548899001",
    partnerId: "website",
    date: "2026-08-27",
    packageName: "2 Seater Buggy 699AED",
    pickupLocation: "Desert Meeting Point, Margham",
    roomNo: "",
    pickupTime: "4:30 PM",
    pax: 2,
    price: 699,
    driverId: "driver-abbasi",
    status: "completed",
    addonName: "",
    addonPrice: 0,
    carPax: "2/6",
    tourType: "self_drive",
    paymentOption: "Payment on Arrival"
  },
  {
    id: "1000112",
    customerName: "Omar Al Hashimi",
    whatsapp: "+971502233445",
    partnerId: "website",
    date: "2026-08-26",
    packageName: "Evening+Quadbike 199AED",
    pickupLocation: "Caesars Palace, Bluewaters Dubai",
    roomNo: "Room 415",
    pickupTime: "3:30 PM to 4:00 PM",
    pax: 3,
    price: 597,
    driverId: "driver-shahmir",
    status: "completed",
    addonName: "",
    addonPrice: 0,
    carPax: "3/6",
    tourType: "pick_drop",
    paymentOption: "Payment on Arrival"
  }
];
